### ISSUE TITLE
Failed to start CLI/Worker in standalone Ruby

### ISSUE THREAD

**Issue by stephenrob** [reidmorrison/rocketjob#22]
### Environment

Provide at least:
* Ruby Version. - 2.7.2
* Rocket Job Version. - 6.0.0.beta (referenced as GitHub Master
* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.). N/A Standalone ruby

### Expected Behaviour

Hello World example should run without any framework.

#### Job (jobs/hello_world_job.rb)
```ruby
class HelloWorldJob < RocketJob::Job
  def perform
    puts "Hello World"
  end
end
```

### Actual Behaviour

Following the 'HelloWorld' example with the basic job and trying to start the RocketJob worker leads to an error trying to load the relational job.

```shell
❯ bundle exec rocketjob
2021-05-16 11:54:26.239538 I [3734:rocketjob main] RocketJob::CLI -- Rails not detected. Running standalone: development
bundler: failed to load command: rocketjob (/Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bin/rocketjob)
LoadError: cannot load such file -- active_record
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/jobs/re_encrypt/relational_job.rb:1:in `require'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/jobs/re_encrypt/relational_job.rb:1:in `<top (required)>'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/cli.rb:167:in `require'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/cli.rb:167:in `block in eager_load_jobs'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/cli.rb:163:in `each'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/cli.rb:163:in `eager_load_jobs'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/cli.rb:116:in `boot_standalone'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/lib/rocket_job/cli.rb:43:in `run'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bundler/gems/rocketjob-96792dfeaa03/bin/rocketjob:8:in `<top (required)>'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bin/rocketjob:23:in `load'
  /Users/stephenrobinson/.rbenv/versions/2.7.2/gemsets/job-scheduler/bin/rocketjob:23:in `<top (required)>'
```

Looking into it the issue it seems to be with the eager loading of the jobs where this is no check for if ActiveRecord or SyncAttr like there is in the main definition where it checks before autoloading the files.

#### lib/rocket_job/cli.rb 167

```ruby
  # Eager load files in jobs folder
  def self.eager_load_jobs(job_path = "jobs")
    Pathname.glob("#{job_path}/**/*.rb").each do |path|
      next if path.directory?

      logger.debug "Loading #{path}"
      require path.expand_path.to_s
    end
  end
```

#### lib/rocketjob.rb 83

```ruby
module ReEncrypt
  if defined?(ActiveRecord) && defined?(SyncAttr)
    autoload :RelationalJob,     "rocket_job/jobs/re_encrypt/relational_job"
  end
end
```

### Pull Request

Happy to submit one if suggestions on the right way forward are given 😄

**Comment by reidmorrison** [comment]
Yes, that Job requires ActiveRecord and SyncAttr. Not sure how you would get the non-rails CLI to not load that job.

**Comment by reidmorrison** [comment]
Could you try wrapping the entire Relational Job code with: 
~~~ruby
if defined?(ActiveRecord) && defined?(SyncAttr)
...
end
~~~

That should prevent Rocket Job from defining that job when those pre-requisites are nor loaded.
