### ISSUE TITLE
RocketJob is throwing exception when trying in standalone mode

### ISSUE THREAD

**Issue by sunilagrya** [reidmorrison/rocketjob#26]
Hi,

When running stand-alone without Rails it is throwing exception.

* Ruby Version 2.7.3.
* Rocket Job Version 6.1.0(Standalone).
* Mongodb 4.4.11
* mongoid (7.3.4)
* mongo (2.17.0)
      bson (>= 4.8.2, < 5.0.0)
* Mac M1

I ran command `bundle exec rocketjob --workers 1`

```
2022-03-01 18:00:49.351551 I [62808:rocketjob main] RocketJob::CLI -- Rails not detected. Running standalone: development
2022-03-01 18:00:49.486705 I [62808:rocketjob main] RocketJob::Supervisor -- Using MongoDB Database: rocketjob_development
2022-03-01 18:00:49.490918 I [62808:rocketjob main] RocketJob::Supervisor -- Rocket Job Server started
2022-03-01 18:00:49.497583 I [62808:rocketjob main] RocketJob::WorkerPool -- Stagger Starting 1 workers
{"$set"=>{"heartbeat.updated_at"=>2022-03-01 18:00:49.498575 +0530, "heartbeat.workers"=>1}}
{:return_document=>:after}
{:findAndModify=>"rocket_job.servers", :query=>{"_id"=>BSON::ObjectId('621e11f96e0652f5583a79ba')}, :update=>{"$set"=>{"heartbeat.updated_at"=>2022-03-01 18:00:49.498575 +0530, "heartbeat.workers"=>1}}, :new=>true}
rocketjob_development
{"$set"=>{"worker_name"=>"Ss-MacBook-Air.local:62808:1", "state"=>"running"}}
{:bypass_document_validation=>true}
{:findAndModify=>"rocket_job.jobs", :query=>{"$or"=>[{"state"=>"queued"}, {"state"=>"running", "sub_state"=>"processing"}], "$and"=>[{"$or"=>[{"run_at"=>nil}, {"run_at"=>{"$lte"=>2022-03-01 12:30:49.498793 UTC}}]}]}, :update=>{"$set"=>{"worker_name"=>"Ss-MacBook-Air.local:62808:1", "state"=>"running"}}, :sort=>{"priority"=>1, "_id"=>1}, :new=>false, :bypassDocumentValidation=>true}
rocketjob_development
2022-03-01 18:00:49.498689 I [62808:rocketjob 001] RocketJob::ThreadWorker -- Started
2022-03-01 18:00:49.499595 I [62808:rocketjob event] RocketJob::Event -- Event listener started
2022-03-01 18:00:49.500525 E [62808:rocketjob main supervisor.rb:49] RocketJob::Supervisor -- RocketJob::Server is stopping due to an exception -- Exception: NoMethodError: undefined method `[]' for nil:NilClass
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongo-2.17.0/lib/mongo/collection/view/writable.rb:200:in `find_one_and_update'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/plugins/document.rb:33:in `find_and_update'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/server/model.rb:112:in `block in refresh'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/semantic_logger-4.10.0/lib/semantic_logger/semantic_logger.rb:463:in `silence'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/server/model.rb:111:in `refresh'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:87:in `block in supervise_pool'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:96:in `synchronize'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:96:in `synchronize'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:87:in `supervise_pool'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:41:in `block (3 levels) in run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/event.rb:70:in `subscribe'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/subscriber.rb:59:in `subscribe'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:40:in `block (2 levels) in run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/event.rb:70:in `subscribe'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/subscriber.rb:59:in `subscribe'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:39:in `block in run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/event.rb:70:in `subscribe'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/subscriber.rb:59:in `subscribe'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:38:in `run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/supervisor.rb:19:in `run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/cli.rb:57:in `run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/bin/rocketjob:8:in `<top (required)>'
/Users/sa/.rbenv/versions/2.7.3/bin/rocketjob:23:in `load'
/Users/sa/.rbenv/versions/2.7.3/bin/rocketjob:23:in `<top (required)>'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
/Users/sa/.rbenv/versions/2.7.3/bin/bundle:23:in `load'
/Users/sa/.rbenv/versions/2.7.3/bin/bundle:23:in `<main>'
2022-03-01 18:00:49.500570 W [62808:rocketjob 001 writable.rb:157] RocketJob::WorkerPool -- Backtrace:
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongo-2.17.0/lib/mongo/collection/view/writable.rb:157:in `write'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongo-2.17.0/lib/mongo/collection/view/writable.rb:157:in `puts'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongo-2.17.0/lib/mongo/collection/view/writable.rb:157:in `puts'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongo-2.17.0/lib/mongo/collection/view/writable.rb:157:in `find_one_and_update'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongoid-7.3.4/lib/mongoid/contextual/mongo.rb:215:in `find_one_and_update'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:160:in `block in find_and_assign_job'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/semantic_logger-4.10.0/lib/semantic_logger/semantic_logger.rb:463:in `silence'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:154:in `find_and_assign_job'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:108:in `next_available_job'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:68:in `run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/thread_worker.rb:13:in `block in initialize'
2022-03-01 18:00:49.500592 I [62808:rocketjob main] RocketJob::Supervisor -- Shutdown Complete
2022-03-01 18:00:49.503263 F [62808:rocketjob 001 worker.rb:84] RocketJob::ThreadWorker -- Unhandled exception in job processing thread -- Exception: NoMethodError: undefined method `[]' for nil:NilClass
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongo-2.17.0/lib/mongo/collection/view/writable.rb:200:in `find_one_and_update'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/mongoid-7.3.4/lib/mongoid/contextual/mongo.rb:215:in `find_one_and_update'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:160:in `block in find_and_assign_job'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/semantic_logger-4.10.0/lib/semantic_logger/semantic_logger.rb:463:in `silence'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:154:in `find_and_assign_job'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:108:in `next_available_job'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/worker.rb:68:in `run'
/Users/sa/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rocketjob-6.1.0/lib/rocket_job/thread_worker.rb:13:in `block in initialize'
```

I have also never used mongoid before, So just added `puts` in some-places  to debug

**Comment by reidmorrison** [comment]
Have not tried Rocket Job in standalone mode in a very long time, let me give it a try locally. I need to create a Dockerfile to make it easier to try out this scenario.

**Comment by reidmorrison** [comment]
The documentation was out of date for the latest mongoid and mongo ruby driver versions. Updated the documentation and verified the configuration file locally. Please re-open this issue if you run into any issues with the latest documentation.
